---
version: "3.7"

services:

  service:
    build: .
    ports:
      - 8080:8080
      - 8081:8081

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-configuration:/etc/prometheus/

  configuration:
    build: infrastructure
    volumes:
      - prometheus-configuration:/etc/prometheus/

volumes:
  prometheus-configuration: