---
version: "3.7"

services:

  service:
    build: .
    ports:
      - 8080:8080
      - 8081:8081

  prometheus:
    image: prom/prometheus:v2.8.0
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:6.0.1
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: foobar
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./infrastructure/grafana/:/etc/grafana/provisioning/

