---
version: '2.4'

services:

  app:
    build: .
    mem_limit: 64M
    scale: 2

  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus/:/etc/prometheus/
    mem_limit: 64M

  grafana:
    image: grafana/grafana:6.2.5
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: "Editor"
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning/
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    mem_limit: 64M
