scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'go-services'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - app
        type: 'A'
        port: 8081
    relabel_configs:
      - source_labels: ['__meta_dns_name']
        target_label: application